processors:
  # Graph-refining processors:
  - inheritance
  - filter_methods # Throw out filtered methods
  - default_constructor # Create default constructors where possible
  - copy_structs # Copy structures as marked
  - macros # Support for macro mapping
  - auto_container_instantiation
  - instantiate_containers # Actually instantiate containers
  - qt # Qt specifics
  # Preliminary generation processors:
  - crystal_wrapper # Create Crystal wrappers
  - virtual_override # Allow overriding C++ virtual methods
  - cpp_wrapper # Create C++ <-> C wrappers
  - crystal_binding # Create `lib` bindings for the C wrapper
  - sanity_check # Shows issues, if any

generators:
  cpp:
    output: ext/qt_binding.cpp
    preamble: |-
      #include "converters.hpp"
    build: make
  crystal:
    output: src/qt5/binding.cr
